name: Lint Code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  html-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: HTML Hint (Linter)
        uses: htmlhint/htmlhint-action@v2
        with:
          addresses: './**/*.html'
